# Setup
title: Sieze The Day !
description:  Repository For Computer Algorithm
url: https://hyunnna.github.io/algorithm/
avatar: /me.jpg
paginate: 5
permalink: pretty
cover_image: /blue.jpg
logo-icon: "/symbol/simbol.svg"
logo-icon-SEO: "/symbol/simbol.svg"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

#Disqus
discus_identifier: hyunnna-github-io # Add your discus identifier
comments_curtain: yes # leave empty to show the disqus embed directly

# Optimize Jekyl SEO Tag
instagram:
  username: _h_hwa
  card: summary
logo: link.png
social:
  name: HyunHwa Jung
  links:
    - https://www.instagram.com/_h_hwa
    - https://github.com/hyunnna
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options
# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: HyunHwa
  url: https://github.com/hyunnna/
  email: wjdgusghk904@naver.com
